'use strict'

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
export const RESET_COUNTER = "RESET_COUNTER"
export const ADD_ITEM = "ADD_ITEM"
